"""auto_migration_20251204_223523

Revision ID: 48a6068d3125
Revises: df6e06b32c92
Create Date: 2025-12-04 22:35:25.941043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a6068d3125'
down_revision: Union[str, Sequence[str], None] = 'df6e06b32c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hackathons_registration_deadline'), 'hackathons', ['registration_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackathons_registration_deadline'), table_name='hackathons')
    # ### end Alembic commands ###
