"""Initial migration - Create all tables

Revision ID: df6e06b32c92
Revises: 
Create Date: 2025-12-04 22:13:55.854693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6e06b32c92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Create all tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create skills table
    op.create_table(
        'skills',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)

    # Create hackathons table
    op.create_table(
        'hackathons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('registration_deadline', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathons_id'), 'hackathons', ['id'], unique=False)
    op.create_index(op.f('ix_hackathons_title'), 'hackathons', ['title'], unique=False)
    op.create_index(op.f('ix_hackathons_location'), 'hackathons', ['location'], unique=False)
    op.create_index(op.f('ix_hackathons_start_date'), 'hackathons', ['start_date'], unique=False)
    op.create_index(op.f('ix_hackathons_end_date'), 'hackathons', ['end_date'], unique=False)

    # Create hackathon_participations table
    op.create_table(
        'hackathon_participations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hackathon_id', sa.Integer(), nullable=False),
        sa.Column('place', sa.Integer(), nullable=True),
        sa.Column('team_name', sa.String(length=255), nullable=False),
        sa.Column('project_link', sa.String(length=255), nullable=True),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_participations_id'), 'hackathon_participations', ['id'], unique=False)
    op.create_index(op.f('ix_hackathon_participations_hackathon_id'), 'hackathon_participations', ['hackathon_id'], unique=False)

    # Create users table
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tg_id', sa.BigInteger(), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('bio', sa.Text(), nullable=False),
        sa.Column('main_role', sa.Enum('backend', 'frontend', 'design', 'pm', 'analyst', name='role'), nullable=True),
        sa.Column('ready_to_work', sa.Boolean(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('tg_username', sa.String(length=255), nullable=True),
        sa.Column('hide_tg_username', sa.Boolean(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)

    # Create teams table
    op.create_table(
        'teams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('captain_id', sa.Integer(), nullable=False),
        sa.Column('leader_id', sa.Integer(), nullable=True),
        sa.Column('hackathon_id', sa.Integer(), nullable=False),
        sa.Column('is_looking', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['team_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_captain_id'), 'teams', ['captain_id'], unique=False)
    op.create_index(op.f('ix_teams_is_looking'), 'teams', ['is_looking'], unique=False)

    # Create achievements table
    op.create_table(
        'achievements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('icon_url', sa.String(length=500), nullable=True),
        sa.Column('unlocked_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)

    # Create requests table
    op.create_table(
        'requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('receiver_id', sa.Integer(), nullable=True),
        sa.Column('team_id', sa.Integer(), nullable=True),
        sa.Column('hackathon_id', sa.Integer(), nullable=False),
        sa.Column('request_type', sa.Enum('join_team', 'collaborate', name='requesttype'), nullable=False),
        sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'canceled', name='requeststatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)

    # Create join_requests table
    op.create_table(
        'join_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'canceled', name='requeststatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_id'), 'join_requests', ['id'], unique=False)

    # Create user_skills association table
    op.create_table(
        'user_skills',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )

    # Create user_participations association table
    op.create_table(
        'user_participations',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('participation_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['participation_id'], ['hackathon_participations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'participation_id')
    )

    # Add foreign key for team_id in users table
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Drop all tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key first
    op.drop_constraint('fk_users_team_id', 'users', type_='foreignkey')
    
    # Drop association tables
    op.drop_table('user_participations')
    op.drop_table('user_skills')
    
    # Drop main tables
    op.drop_table('join_requests')
    op.drop_table('requests')
    op.drop_table('achievements')
    op.drop_table('teams')
    op.drop_table('users')
    op.drop_table('hackathon_participations')
    op.drop_table('hackathons')
    op.drop_table('skills')
    
    # Drop enums
    sa.Enum('backend', 'frontend', 'design', 'pm', 'analyst', name='role').drop(op.get_bind())
    sa.Enum('join_team', 'collaborate', name='requesttype').drop(op.get_bind())
    sa.Enum('pending', 'accepted', 'declined', 'canceled', name='requeststatus').drop(op.get_bind())

    # ### end Alembic commands ###
